import re, subprocess, time, pathlib, sys, json
from playwright.sync_api import sync_playwright
HERE = pathlib.Path(__file__).resolve().parent
root = HERE.parent
out = HERE / "out"
out.mkdir(exist_ok=True)
data = json.loads((HERE / "fixture.json").read_text(encoding="utf-8"))
html = (root / "index.html").read_text(encoding="utf-8")
html = re.sub(r"var firebaseConfig = \{[\s\S]*?\n  \};", 'var firebaseConfig = {apiKey:"invalid",authDomain:"invalid.firebaseapp.com",projectId:"invalid-offline-test"};', html)
html = html.replace("boot();", "window.__t={state:function(){return state;},setTab:setTab,render:render,setSync:function(m){syncMeta=m;paintSyncPill();},setLoaded:function(v){db=v?{}:null;loaded.products=!v;render();}}; boot();", 1)
(root / "_p_copy.html").write_text(html, encoding="utf-8")
srv = subprocess.Popen([sys.executable, "-m", "http.server", "8780", "--directory", str(root)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(1.5)
try:
    with sync_playwright() as p:
        b = p.chromium.launch()
        pg = b.new_page(viewport={"width": 390, "height": 844}, has_touch=True, is_mobile=True)
        errs = []; pg.on("pageerror", lambda e: errs.append(str(e)))
        reqs = []; pg.on("request", lambda r: reqs.append(r.url))
        pg.goto("http://localhost:8780/_p_copy.html#sales"); pg.wait_for_timeout(1800)
        pg.evaluate("(d) => { const S = window.__t.state(); ['products','batches','sales','settlements'].forEach(k => { S[k] = d[k]; }); window.__t.render(); }", data)
        print("hash start tab:", pg.evaluate("document.body.dataset.tab"), "| tesseract loaded at start:", any("tesseract" in u for u in reqs))
        print("chips:", pg.locator(".fchip").all_inner_texts())
        pg.click(".fchip:has-text('Unassigned')"); pg.wait_for_timeout(200)
        print("unassigned rows:", pg.locator(".sale-row").count())
        pg.click(".fchip:has-text('All')"); pg.wait_for_timeout(200)
        pg.click("#salesSearch"); pg.keyboard.type("pikachu", delay=40); pg.wait_for_timeout(400)
        print("search 'pikachu' rows:", pg.locator(".sale-row").count(), "| focus kept:", pg.evaluate("document.activeElement.id"), "| value:", pg.input_value("#salesSearch"))
        pg.fill("#salesSearch", "zzzz"); pg.wait_for_timeout(400)
        print("no-match msg:", pg.locator(".card.empty").last.inner_text().strip()[:60])
        pg.fill("#salesSearch", ""); pg.wait_for_timeout(300)
        pg.evaluate("window.__t.setSync({lastSync: Date.now()-3*60000})"); print("pill:", pg.inner_text("#syncPill"))
        pg.evaluate("window.__t.setSync({lastSync: Date.now()-47*60000})"); print("pill stale:", pg.inner_text("#syncPill"), pg.get_attribute("#syncPill","class"))
        pg.evaluate("window.__t.setSync({lastSync: Date.now()-2*60000})")
        pg.click(".bottom-tabbar .navbtn[data-tab='overview']"); pg.wait_for_timeout(400)
        print("after nav click hash:", pg.evaluate("location.hash"), "tab:", pg.evaluate("document.body.dataset.tab"))
        pg.screenshot(path=str(out / "p_over.png"), full_page=False)
        pg.go_back(); pg.wait_for_timeout(300); print("back ->", pg.evaluate("document.body.dataset.tab"))
        pg.evaluate("window.__t.setTab('inventory')"); pg.wait_for_timeout(300)
        pg.fill("#invSearch", "nami"); pg.wait_for_timeout(400)
        print("inv search nami:", pg.locator(".product-card").count(), pg.inner_text(".section-head .count"))
        pg.fill("#invSearch", ""); pg.wait_for_timeout(300)
        # modal focus restore
        pg.evaluate("window.__t.setTab('sales')"); pg.wait_for_timeout(300)
        btn = pg.locator("button[data-action='open-add-sale']").first; btn.focus(); btn.click(); pg.wait_for_timeout(300)
        print("modal open focus in modal:", pg.evaluate("!!document.activeElement.closest('.modal')"))
        for _ in range(30): pg.keyboard.press("Tab")
        print("focus trapped in modal after 30 tabs:", pg.evaluate("!!document.activeElement.closest('.modal')"))
        pg.keyboard.press("Escape"); pg.wait_for_timeout(200)
        print("focus restored to trigger:", pg.evaluate("document.activeElement.dataset.action"))
        # skeleton
        pg.evaluate("window.__t.setLoaded(true)"); pg.wait_for_timeout(200)
        print("skeleton shown:", pg.locator(".sk").count() > 0, "aria-busy:", pg.get_attribute("#main","aria-busy"))
        pg.evaluate("window.__t.setLoaded(false)")
        pg.evaluate("window.__t.setTab('overview')"); pg.wait_for_timeout(300)
        pg.screenshot(path=str(out / "p_over_full.png"), full_page=True)
        print("scrollW", pg.evaluate("document.documentElement.scrollWidth"), "errors:", errs)
        b.close()
finally:
    srv.terminate(); (root / "_p_copy.html").unlink(missing_ok=True)
